---
linters:
  eslint:
    config: './eslint.config'
  csslint:
    ignore: 'box-model,ids'

fixers:
  enable: true

files:
  # Ignore the files that match these glob patterns.
  # Be careful to quote strings as `*` has special
  # meaning in YAML files.
  ignore:
  - 'src/generated/*'
  - 'node_modules/*'