import { zipObject } from 'lodash';

const ACTION_TYPES = [
  'RECEIVE_REGISTER_RESPONSE',

  'LOGIN_REQUEST_ATTEMPTED',
  'RECEIVE_LOGIN_REQUEST_SUCCESS',
  'RECEIVE_LOGIN_REQUEST_FAILURE',

  'LOGOUT_REQUEST_ATTEMPTED',
  'RECEIVE_LOGOUT_REQUEST_SUCCESS'
];

export default zipObject(ACTION_TYPES, ACTION_TYPES);